[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "storybear"
description = "Pipeline to add some magic for data storytelling"

authors = [
  {name = "Tatiana Malygina"},
]
maintainers = [
  {name = "Tatiana Malygina"}
]
version = "2026.06.07"
dependencies = [
    "numpy",
    "scipy",
    "tqdm",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "rootutils",
    "gradio",
    "click",
    "python-docx",
    "transformers>=5.6,<6",
    "torch>=2.11",
    "accelerate",
    "diffusers",
    "sentence_transformers",
    "umap-learn",
    "partialsmiles",
    "pypalettes",
    "fpdf2"
]

readme = "readme.md"

requires-python = ">=3.10"

[project.scripts]
storytell = "storybear:main_cli"
storygen = "storybear:generate_data_cli"

[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
"*" = [".project-root"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Repository = "https://github.com/latticetower/storybear.git"
