"""
stages.py
=========
Pipeline stages 3-9.

Each class is independently instantiable and testable.
They share no global state — data flows through method arguments and return values.

LLM calls
---------
Every class that uses an LLM exposes a `_call_llm(prompt: str) -> str` helper
that you replace with your actual API call (OpenAI, Anthropic, etc.).
A system prompt class variable (`SYSTEM_PROMPT`) is also provided for easy
customisation without subclassing.

Stage map
---------
3. Captionist   — PlotRecord  → CaptionedRecord   (LLM)
4. Foodie       — CaptionedRecord → RankedRecord  (LLM, vision)
5. Secretary    — list[RankedRecord] → list[RankedRecord]  (top-N selector)
-- 6. Editor       — list[RankedRecord] → ReportMeta (LLM)
-- 7. Junior       — list[RankedRecord] + ReportMeta → list[OrderedRecord]  (LLM)
-- 8. Artist       — list[OrderedRecord] → list[FinalRecord] (LLM, vision, in-place edit)
-- 9. Typography   — list[FinalRecord] + ReportMeta → Path (.docx)
"""

from __future__ import annotations

import base64
import json
import logging
from pathlib import Path
from typing import Any
# TODO: debug
import matplotlib.pyplot as plt


from storybear.data_structures import (
    PlotRecord,
    ReportRecord,
)

logger = logging.getLogger(__name__)

from .base import _LLMMixin

# ---------------------------------------------------------------------------
# 3. Captionist
# ---------------------------------------------------------------------------


class Captionist(_LLMMixin):
    """
    Step 3 — Generates a natural-language caption C for each plot P.

    For every PlotRecord it receives the plot image (via vision LLM) and the
    associated statistics dict, and asks the LLM to produce a concise,
    insightful description suitable for a data-journalism report.

    Parameters
    ----------
    max_caption_words:
        Soft word-count target passed to the LLM in the prompt.
    """

    SYSTEM_PROMPT = (
        "You are a data journalist writing captions for statistical charts. "
        "Be concise, precise, and highlight the most surprising finding."
    )

    def __init__(self, max_caption_words: int = 60) -> None:
        self.max_caption_words = max_caption_words

    def process(self, plot_record: PlotRecord) -> PlotRecord:
        """Generate a caption for a single PlotRecord."""
        prompt = self._build_prompt(plot_record)
        caption = self._call_llm_vision(prompt, plot_record.plot_path)
        return PlotRecord(plot_record=plot_record, caption=caption.strip())

    def process_all(self, plot_records: list[PlotRecord]) -> list[PlotRecord]:
        """Process every PlotRecord in the list."""
        results: list[PlotRecord] = []
        for i, record in enumerate(plot_records):
            logger.info("Captionist: %d/%d — %s", i + 1, len(plot_records), record.plot_path.name)
            results.append(self.process(record))
        return results

    def _build_prompt(self, record: PlotRecord) -> str:
        stats_str = json.dumps(record.stats, indent=2) if record.stats else "(none)"
        return (
            f"This chart was generated by the '{record.plotter_class}' plotter "
            f"for column(s): {', '.join(record.columns)}.\n\n"
            f"Statistical summary:\n{stats_str}\n\n"
            f"Write a caption of at most {self.max_caption_words} words that "
            "describes the key finding visible in the chart."
        )







